version: '3.2'
services:
  nest-project:
    build:
      context: .
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=submission
    volumes:
      - submission_db:/var/lib/postgresql/data

volumes:
  submission_db:
